version: '2'
services:
  bot:
    image: node:latest
    command: bin/hubot -a slack
    working_dir: /usr/src/app
    volumes:
      - "$PWD:/usr/src/app"
    environment:
      - HUBOT_SLACK_TOKEN
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: always
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - '/var/redis:/data'
    restart: always
